export const FETCH_GAMES_REQUEST = 'FETCH_GAMES_REQUEST';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAILURE = 'FETCH_GAMES_FAILURE';

export const FETCH_POPULAR_GAMES_REQUEST = 'FETCH_POPULAR_GAMES_REQUEST';
export const FETCH_POPULAR_GAMES_SUCCESS = 'FETCH_POPULAR_GAMES_SUCCESS';
export const FETCH_POPULAR_GAMES_FAILURE = 'FETCH_POPULAR_GAMES_FAILURE';

export const FETCH_PLATFORMS_REQUEST = 'FETCH_PLATFORMS_REQUEST';
export const FETCH_PLATFORMS_SUCCESS = 'FETCH_PLATFORMS_SUCCESS';
export const FETCH_PLATFORMS_FAILURE = 'FETCH_PLATFORMS_FAILURE';

export const FETCH_GENRES_REQUEST = 'FETCH_GENRES_REQUEST';
export const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS';
export const FETCH_GENRES_FAILURE = 'FETCH_GENRES_FAILURE';

export const SET_FILTER_BY_RATING = 'SET_FILTER_BY_RATING';
export const SET_FILTER_BY_YEAR = 'SET_FILTER_BY_YEAR';
