export const FETCH_NEWS_REQUEST = 'FETCH_NEWS_REQUEST';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAILURE = 'FETCH_NEWS_FAILURE';

export const FETCH_NEWS_BY_CATEGORY_REQUEST = 'FETCH_NEWS_BY_CATEGORY_REQUEST';
export const FETCH_NEWS_BY_CATEGORY_SUCCESS = 'FETCH_NEWS_BY_CATEGORY_SUCCESS';
export const FETCH_NEWS_BY_CATEGORY_FAILURE = 'FETCH_NEWS_BY_CATEGORY_FAILURE';

export const CREATE_NEWS_REQUEST = 'CREATE_NEWS_REQUEST';
export const CREATE_NEWS_SUCCESS = 'CREATE_NEWS_SUCCESS';
export const CREATE_NEWS_FAILURE = 'CREATE_NEWS_FAILURE';

export const SET_CURRENT_PAGE = 'NEWS/SET_CURRENT_PAGE';
